### ISSUE TITLE
Should we update miniconda version?

### ISSUE THREAD

**Issue by RainierBarrett** [cmelab/containers#26]
Our frozen miniconda ver in the gpuhoomd file is one minor version behind, which slows down builds derived from that container that need to `conda update conda`. Should we:

-  switch to latest instead and rebuild periodically?
- just move to the most recent frozen version manually? 
- leave it alone?

**Comment by erjank** [comment]
I vote for moving to most recent frozen version manually

**Comment by chrisjonesBSU** [comment]
I think we should pin the most recent version, but also check and update periodically so we don't run into this same issue again.

**Comment by RainierBarrett** [comment]
Should be addressed by https://github.com/cmelab/containers/pull/27, but gonna re-build from scratch just to be sure
