### ISSUE TITLE
We need hoomd3 GPU containers

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/containers#5]
With support for hoomd2 ending, and our packages updating to hoomd3, we should add a container that compiles hoomd3 for GPU.

**Comment by erjank** [comment]
Skip this for HOOMD4?

**Comment by chrisjonesBSU** [comment]
Maye..I wonder if we should open an issue about how to structure this repo.

It would be nice to have a set of stable, well-tested containers when needed. But it would also be nice to have containers in place for easily trying and testing bleeding edge stuff.

What if we did something like:

- containers/
    - stable/
        - condagpu_stable (pinned versions of conda, CUDA, etc...)
            - hoomd4
                - containers for our wrapper repos (hoomd-polymers, msibi, etc...)
            - hoomd3
                - containers for our wrapper repos (hoomd-polymers, msibi, etc...)
            - hoomd2 
                - older plankton container? msibi container (still using hoomd2 technically; working on updating to hoomd3)
            - hoomd_tf 
            
    - latest/
        - condagpu_latest (use the latest versions of conda, CUDA, other packages, etc...)
            - hoomd4
                - containers for our wrapper repos (hoomd-polymers, msibi, etc...)
            - hoomd_tf_dev

Maybe this is doing too much?
